name: Publish Documentation
on:
  push:
    tags: '*'
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.12 
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install -E amazon -E docs

      - name: Build documentation
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/
          poetry run sphinx-build -b html . _build
          cp -r _build/* ../gh-pages/        

      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages
